-- Limpa a tabela antes de inserir para evitar duplicados (opcional)
-- TRUNCATE TABLE ruas;

-- Inserção de todas as ruas e localidades
-- Nota: A tabela ruas deve ser criada primeiro via historico_trabalhos.sql
-- Usa N'' prefix para suporte Unicode em NVARCHAR
INSERT INTO ruas (nome_rua, localidade) VALUES 
(N'Estrada da Castanheira - Parque Alfocheira', N'Alfocheira'),
(N'Rua do Lameiro', N'Alfocheira'),
(N'Rua dos Baldios de Alfocheira', N'Alfocheira'),
(N'Rua dos Quatro Balcões', N'Alfocheira'),
(N'Rua Nossa Senhora da Memória', N'Alfocheira'),
(N'Rua 25 de Abril', N'Bairro dos Carvalhos'),
(N'Rua Augusto Miguel', N'Bairro dos Carvalhos'),
(N'Rua Combatentes do Ultramar', N'Bairro dos Carvalhos'),
(N'Rua Jorge Carvalho', N'Bairro dos Carvalhos'),
(N'Rua Luís Manaia', N'Bairro dos Carvalhos'),
(N'Rua Manuel Albergaria Pinheiro e Silva', N'Bairro dos Carvalhos'),
(N'Rua Orlando Francisco Alvarinhas', N'Bairro dos Carvalhos'),
(N'Beco da Cavada', N'Cabeço do Moiro'),
(N'Rua do Brejo', N'Cabeço do Moiro'),
(N'Rua do Depósito', N'Cabeço do Moiro'),
(N'Rua S. Bento', N'Cabeço do Moiro'),
(N'Travessa da Cavada', N'Cabeço do Moiro'),
(N'Alameda Desembargador António Cardoso Faria Pinto', N'Cabo do Soito'),
(N'Avenida Coelho da Gama', N'Cabo do Soito'),
(N'Avenida São Silvestre', N'Cabo do Soito'),
(N'Bairro dos Cândidos', N'Cabo do Soito'),
(N'Beco do Pinheiro', N'Cabo do Soito'),
(N'Caminho Senhora das Barraquinhas', N'Cabo do Soito'),
(N'Largo da Filarmónica Lousanense', N'Cabo do Soito'),
(N'Rua de São Silvestre', N'Cabo do Soito'),
(N'Rua do Calvário', N'Cabo do Soito'),
(N'Rua do Carrascal', N'Cabo do Soito'),
(N'Rua do Soito', N'Cabo do Soito'),
(N'Rua dos Cândidos', N'Cabo do Soito'),
(N'Rua Dr. Pires de Carvalho', N'Cabo do Soito'),
(N'Rua Gil Vicente', N'Cabo do Soito'),
(N'Rua Professor Dr. José Maria de Queirós e Vasconcelos', N'Cabo do Soito'),
(N'Travessa do Soito', N'Cabo do Soito'),
(N'Beco de Carvalhal de Baixo', N'Carvalhal de Baixo'),
(N'Caminho de Carvalhal de Baixo', N'Carvalhal de Baixo'),
(N'Rua de Carvalhal de Baixo', N'Carvalhal de Baixo'),
(N'Rua de Santo António', N'Carvalhal de Baixo'),
(N'Rua do Carvalhal', N'Carvalhal de Baixo'),
(N'Rua do Carrascal', N'Carvalhal de Cima'),
(N'Rua do Vale', N'Carvalhal de Cima'),
(N'Rua dos Carvalhinhos', N'Carvalhal de Cima'),
(N'Rua Principal de Carvalhal de Cima', N'Carvalhal de Cima'),
(N'Beco da Fonte', N'Cativa'),
(N'Rua da Cativa', N'Cativa'),
(N'Rua da Corredoura', N'Cativa'),
(N'Rua da Fonte', N'Cativa'),
(N'Rua do Lameiro', N'Cativa'),
(N'Rua do Olival', N'Cativa'),
(N'Rua Dr. Germano de Vasconcelos', N'Cativa'),
(N'Caminho da Ribeira', N'Favela'),
(N'Caminho de Favela', N'Favela'),
(N'Rua de Favela', N'Favela'),
(N'Rua do Olival', N'Favela'),
(N'Rua Principal de Favela', N'Favela'),
(N'Bairro da Quinta de Santo António', N'Lousã'),
(N'Beco de Vale de Milho', N'Lousã'),
(N'Caminho de Santa Rita', N'Lousã'),
(N'Estrada da Lousã', N'Lousã'),
(N'Largo de Santa Rita', N'Lousã'),
(N'Praceta de Santa Rita', N'Lousã'),
(N'Rua Dr. Germano de Vasconcelos', N'Lousã'),
(N'Rua Marquês de Pombal', N'Lousã'),
(N'Beco da Amieira', N'Póvoa de Fiscal'),
(N'Caminho da Amieira', N'Póvoa de Fiscal'),
(N'Rua da Amieira', N'Póvoa de Fiscal'),
(N'Rua de Santo António', N'Póvoa de Fiscal'),
(N'Rua do Fiscal', N'Póvoa de Fiscal'),
(N'Rua Principal de Póvoa de Fiscal', N'Póvoa de Fiscal'),
(N'Rua da Capela', N'Prilhão'),
(N'Rua de Prilhão', N'Prilhão'),
(N'Rua do Vale', N'Prilhão'),
(N'Rua Principal de Prilhão', N'Prilhão'),
(N'Rua de Reguengo', N'Reguengo'),
(N'Rua do Vale', N'Reguengo'),
(N'Rua Principal de Reguengo', N'Reguengo'),
(N'Rua de Vale Neira', N'Vale Neira'),
(N'Rua do Vale', N'Vale Neira'),
(N'Rua Principal de Vale Neira', N'Vale Neira'),
(N'Rua de Vale Nogueira', N'Vale Nogueira'),
(N'Rua Principal de Vale Nogueira', N'Vale Nogueira'),
(N'Rua de Vale Pereira do Areal', N'Vale Pereira do Areal'),
(N'Rua Principal de Vale Pereira do Areal', N'Vale Pereira do Areal');